<?php 
//DEFAULT VALUE
if (!defined('DEFAULT_MAX_LOGIN_ATTEMPTS')) define('DEFAULT_MAX_LOGIN_ATTEMPTS', 5);
if (!defined('DEFAULT_ACCOUNT_EXPIRY_DAYS')) define('DEFAULT_ACCOUNT_EXPIRY_DAYS', 365);

if (!defined('MAX_LOGIN_ATTEMPTS')) define('MAX_LOGIN_ATTEMPTS', 'MAX_LOGIN_ATTEMPTS');
if (!defined('ACCOUNT_EXPIRY_DAYS')) define('ACCOUNT_EXPIRY_DAYS', 'ACCOUNT_EXPIRY_DAYS');